server:
  port: 80
#jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stu?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123
mybatis:
  type-aliases-package: com.qhit.demo.pojo
